### ISSUE TITLE
Java Socket Closed

### ISSUE THREAD

**Issue by SugarBlank** [ultranity/Pix-EzViewer#48] opened 2021-04-07 02:58 UTC
**Bug Details**
Cannot log into the app due to "Socket is closed"

**To Reproduce**
1. Enter details of your account
2. Try to log in

**Expected behavior**
Being able to log into my account and using the app.

**Smartphone Info:**
 - Device: Google Pixel 4a
 - OS: Android 11
 - Version: 1.7.7
![IMG_20210406_225723.png](https://user-images.githubusercontent.com/64178604/113803934-8672f200-972b-11eb-859f-b013f95a62d3.png)

**Comment by namazso** [comment] 2021-04-13 23:37
duplicate of #47 #46, login needs to be replaced with web login, as old pixiv app token can no longer authenticate.
related pixez-flutter commit: https://github.com/Notsfsssf/pixez-flutter/commit/513e6e3847256b9187585d6fc100e7d7da245f25
needs to be implemented here

**Comment by SugarBlank** [comment] 2021-04-14 00:07
Haha, I didn't see the other issues posted, my bad. I'll see if I can set up the new login way on my end and make a pull request, thanks for providing an example.

**Closed** 2021-11-07 05:53 UTC

**Comment by ultranity** [comment] 2021-11-07 09:29
please update to 1.8.0+
